name: Build Kernel

on:
  push:
    branches: q
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: everclearecct/android-kernel-actions@master
      id: build
      env:
        NAME: kernel build
      with:
        arch: arm64
        compiler: gcc/8
        defconfig: aoscp_bullhead_defconfig
        image: Image.gz-dtb
        python_version: 2

    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
